version: '2'

volumes:
  nextcloud:
  db:

services:


            
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bolson
      - MYSQL_PASSWORD=bolson
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  s1:
    image: nextcloud
    hostname: s1
    container_name: s1
    restart: always
    expose:
      - 80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=bolson
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  s2:
    image: nextcloud
    hostname: s2
    container_name: s2
    restart: always
    expose:
      - 80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=bolson
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  haproxy_img:
    build: ./haproxy/
    ports:
      - "8383:80"
    depends_on:
      - s1
      - s2